### ISSUE TITLE
The attached projects cannot be found

### ISSUE THREAD

**Issue by xuan2261** [dr4k0nia/Unscrambler#1]
I can't find the four project attached as shown below, can you upload it?
Thank you very much.
![image](https://user-images.githubusercontent.com/17797687/97806203-0a144880-1c8d-11eb-9e9c-dae2374a5fb2.png)

**Comment by dr4k0nia** [comment]
~AsmResolver is included as a submodule make sure to use `git clone --recursive` to include the submodules.~

**Edit: (13/11/2020) This is now redundant since I switched to the NuGet package of AsmResolver.**
